name: base
channels:
  - defaults
dependencies:
  - pip:
    - cachetools==5.2.1
    - google-api-core==2.11.0
    - google-api-python-client==2.73.0
    - google-auth==2.16.0
    - google-auth-httplib2==0.1.0
    - google-auth-oauthlib==0.8.0
    - googleapis-common-protos==1.58.0
    - gspread==5.7.2
    - httplib2==0.21.0
    - mysqlclient==2.1.0
    - oauth2client==4.1.3
    - oauthlib==3.2.2
    - pgdb==0.0.11
    - protobuf==4.21.12
    - psycopg2-binary==2.9.4
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pydoe2==1.3.0
    - pygsheets==2.0.6
    - requests-oauthlib==1.3.1
    - retry==0.9.2
    - rsa==4.9
    - uritemplate==4.1.1
    - woocommerce==3.0.0